### ISSUE TITLE
TMT 11 support ?

### ISSUE THREAD

**Issue by lars20070** [sangtaekim/msgfplus#22]
Does the current version of MS-GF+ support TMT 11? The `-protocol` option only specifies `TMT`. In our tests we get only very few PSMs.

**Comment by alchemistmatt** [comment]
Yes, it supports TMT11.  Since you closed the issue, I'm going to guess you had your fixed (static) mod masses incorrect.  You should use:
```
# Static mods
229.1629,*,fix,N-term,TMT6plex
229.1629,K,fix,any,TMT6plex
```
Note that the mod mass to use for TMT11 is the same as the one used for TMT6 and TMT10.  Also, MSGF+ will auto-select the TMT protocol if it detects the TMT static mod (leave off `-protocol` and the console output should still say `Protocol: TMT`).  Finally, note that if you are searching for TMT-labelled phosphopeptides, you should use `-protocol 1` to enable `Protocol: Phosphorylation`.
